### ISSUE TITLE
Can you public pretrain models?

### ISSUE THREAD

**Issue by ngocanh2162** [JabuMlDev/Speaker-VGG-CCT#1]

**Comment by JabuMlDev** [comment]
Hi, sorry for the delay.

We have not released any pre-trained models because this project is a research work.

As you can see, all scripts are written to test the performance of cross-corpus models using a particular cross-validation technique.
If you select a set of datasets, there isn't a single pre-trained model but this depends on the corpus you want to use in testing.
You can choose which one to use among the parameters of the various scripts.

However using the project scripts you can train a single model simply. You can find all the instructions on how to do this in the README file.
